### ISSUE TITLE
hostapd: Is this still necessary?

### ISSUE THREAD

**Issue by fkmclane** [pentoo/pentoo-overlay#229]
Version 2.6 of hostapd is in the main Gentoo tree. Additionally, any hostapd after 2.0 is masked in the pentoo profile. Is this mask still necessary and if not, would it be beneficial to drop hostapd in favor of the Gentoo one?

**Comment by blshkv** [comment]
We provide wpe patch which is one of most valuable software for wireless hacking. I have pushed this patch for the latest hostapd but haven't tested it fully yet. 

The short answer is no, we will probably never be able to drop it

**Comment by fkmclane** [comment]
Good to know! I was just curious.

**Comment by blshkv** [comment]
We use official aircrack-ng patch (https://github.com/aircrack-ng/aircrack-ng/tree/master/patches/wpe/hostapd-wpe). I have just checked and it were some changes 27 days ago. I will update it. Meanwhile, I have removed the mask. It's time to start testing it for everyone and report issues to the upstream since they support it.
