### ISSUE TITLE
QA's here now

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#525]
I think we need to freeze current-state versions of all packages, stop bumping of the versions and stabilize the most popular tools in the overlay. At least changing the priority from bumping packages to stabilizing existing ones (lol)

What is the general point:
1) reduce the burden to the Gentoo/Pentoo users (not rare when users get some errors while installing some packages). Try to reduce the number of problems associated with the building/installing and work of packages.

2) transform the general quantity of stabilized and working packages to the main quality of the product.

3) take out/drop the garbage.

I propose to do the following:
1) we need to split the total of packages/categories to everyone member and who has the opportunity to help by making a [pull request](https://github.com/pentoo/pentoo-overlay/pulls) (all of you can take some categories from the repo but you must understand what needs to be done. See links below)

2) looking at commits we can in the one/two month (+/-) to stabilize some amount of the packages and in the next one/two month to bumping versions (consideration req also)...

As a result, we must get accelerated work of the portage with _dependency calculation_ due to fewer problems.

@ZeroChaos-  @blshkv what do you think about it?

Thank you!

More info:
 * https://wiki.gentoo.org/wiki/Basic_guide_to_write_Gentoo_Ebuilds
 * https://wiki.gentoo.org/wiki/Repoman
 * https://dev.gentoo.org/~zmedico/portage/doc/man/repoman.1.html
 * https://wiki.gentoo.org/wiki/Stable_request
 * https://devmanual.gentoo.org/ebuild-maintenance/maintenance-tasks/index.html
 * https://wiki.gentoo.org/wiki/Package_testing
 * https://devmanual.gentoo.org/keywording/index.html
 * https://www.gentoo.org/glep/glep-0040.html#stabling-guidelines-for-all-archs
 * google.com

_P.S. 
Sorry for the quality of my English_ :(

**Comment by linxon** [comment]
app-crypt — is done
```bash
RepoMan scours the neighborhood...
  KEYWORDS.missing              1
   app-crypt/cuda-rarcrypt/cuda-rarcrypt-3.2-r1.ebuild
  file.size                     1
   (22 KiB) app-crypt/hashkill/files/0002-add-openssl-1.1.0-api-support.patch
  upstream.workaround           2
   app-crypt/hashkill/hashkill-0.3.1_p20140204.ebuild: Upstream parallel compilation bug (ebuild calls emake -j1 on line: 104)
   app-crypt/rcracki_mt/rcracki_mt-0.7.0-r1.ebuild: Upstream parallel compilation bug (ebuild calls emake -j1 on line: 65)
```

**Comment by linxon** [comment]
app-exploits — is done
```
RepoMan scours the neighborhood...

Note: use --include-dev (-d) to check dependencies for 'dev' profiles

RepoMan sez: "If everyone were like you, I'd be out of business!"

```

**Comment by ZeroChaos-** [comment]
I bump things as I need to bump them, and that's honestly how things get bumped.  I also go over everything I touch for QA issues, so that happens at near random as well.  I support your effort to establish qa, but know that it isn't an all or nothing process.  we can drop old and dead stuff, we can clean up existing ebuilds, but much of what I put into pentoo is only in pentoo because it violates some gentoo policy and I need it to work anyway ;-)

**Comment by blshkv** [comment]
We have two categories of packages already: the first group which is getting pulled from pentoo-meta (part of iso) and others which are not.
There are few problems which makes our life difficult. The main one is that we rely on Gentoo which is slow AND too fast with bumping/package changes at the same time. Sometimes our tools require the latest package, and we have to fork it. But in some cases, Pentoo tools are not ready for the latest or Gentoo would make an unexpected change which breaks our builds.

As for our side errors, it happens ;-) Like I may forget to try to run a bumped version, push a broken tool. I don't think we are ready to support stable/unstable keywords yet as we don't have resources for that. 

As the outcome, my suggestions are the following:
 - run ```repoman``` and try to keep errors to the minimum (good luck with ruby)
 - make sure that a bumped version builds
 - make sure that it runs.

btw, our ebuilds are getting accepted by Gentoo once in while, and that is our goal eventually.
That's why we have Gentoo developer here ;-)
