### ISSUE TITLE
app-emulation/qemu-charm: drop/upgrade to 4.2.0/replace

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#573]
The current ebuild in the tree relies on an ancient qemu 0.13.0 that cannot be build. I tried updating this one, but the current version is almost a decade old and many options ins the configure file have changed. The ebuild also has a lot of repoman issues. I kind of gave up on this and decided to make an issue to find out what should be done.

**Comment by necrose99** [comment]
@gkroon 
I've been working on a few add libs for qemu charm 
including aarch64 ,  to do is a charm-picker ie 
https://github.com/necrose99/pentoo-overlay 
along with a few rust add ons .. 
anyrate pull my ebuild stash of not in pentoo , oie python for shodan orr etc re-branch them better idea than master or arm64 tracking, 
reset repo hard. 
re-add , 
last few commits weren't signed so pulls sucks. 
but forgot to add gpg back on system since laptop is newish. 

**https://github.com/JamieCruwys/bash-menu-generator**  

could make a quick and dirty arm7hf etc menus  not quite a eselect but enough. 

(S) remove symlinks for arm64 
(s) remove for arm
qemu-aarch64-wrapper.c or other wrappers for commons , 

pick a board style set symlink to wrapper and blam'o ... 

unless new boards or menu is improved ,  dont have to re-emerge. 

pick a system off the menu , removes/sets wrapper 
/usr/quemu-wrapper/s > /usr/bin/quemu-wrapper && quemu-wrapper64

**Comment by necrose99** [comment]
https://github.com/necrose99/pentoo-overlay/tree/charm-changes 
rather have qemu minimal [arm] arm64 ? [qemu-aarch64] 
fixed gpg signing crapolla.

**Comment by blshkv** [comment]
we do not have such ebuild

**Comment by necrose99** [comment]
**app-emulation/qemu [arm] [aarch64]**
https://gitweb.gentoo.org/repo/gentoo.git/tree/app-emulation/qemu/qemu-4.2.0-r2.ebuild 
or greater >=
was stating just using gentoo's in tree .. 

**adding charm set menu** ... pick cpu/s 
via bash / do syms... 
**make ... all gcc quemu wrapper**s ....  /usr/charms/ ->>> /usr/bin/some wrapper link/s... 

wala was an idea to retrofit .

**Comment by necrose99** [comment]
funtoo has a better python script , https://www.funtoo.org/Frankenchroot
https://code.funtoo.org/bitbucket/users/drobbins/repos/fchroot/browse
