### ISSUE TITLE
cuSignal - Add to Package Manager

### ISSUE THREAD

**Issue by rfwill202** [pentoo/pentoo-overlay#671]
Is it possible to make cuSignal available in the package manager?

**Comment by blshkv** [comment]
I took few attempts but decided to give up. The tool needs nvcc (dev-util/nvidia-cuda-toolkit) which require old gcc <sys-devel/gcc-8[cxx] and which is a pain already. Each new bump would be a big deal because upstream changes build.sh daily and we would need to review our ebuild everytime. I don't think it is worth it. 

You should stick with the official way: use conda or docker.
