### ISSUE TITLE
app-exploits/packetstormexploits

### ISSUE THREAD

**Issue by willard-dawson-nyl** [pentoo/pentoo-overlay#89]
I know, this is an annoying topic.  I have to say, putting a fetch restriction with instructions is more of a PITA than the previous issues with the "missing" GoDaddy Secure Server Intermediate Certificate.

IMHO, though, it would be just as easy to write the following instruction to server admins - and with the advantage that it only has to be done once per server:

Download https://certs.godaddy.com/repository/gdig2.crt to /usr/local/share/ca-certificates/
Run update-ca-certificates

I did run into a case where I had to re-run update-ca-certificates, though, even though the cert had previously been installed. Not sure what killed it, but that was easy enough.

I don't suppose there would be a way to make the ebuild depend on the GoDaddy intermediate cert being installed?

**Comment by blshkv** [comment]
This is a long story, see https://code.google.com/archive/p/pentoo/issues/360 for the initial discssion.
I believe that the cert is installed on a client so it has nothing to do with ca-certificates.

The problem is that wget does not support cert chains and fails to validate it. We did try to ask packetstorm guys several times without any success. I've added a fetch restriction because one of pentoo users failed to read an error message.

So here is how to fix the cert on the server:
https://community.qualys.com/thread/12331

Feel free to bug them too...

**Comment by blshkv** [comment]
btw, you will get the following warning if check https://www.ssllabs.com/ssltest/analyze.html?d=dl.packetstormsecurity.net:
```Chain issues	Incomplete```

The current certificate is expiring in 24 days so it should be a right time to contact them.

**Comment by blshkv** [comment]
I sent an email to Todd again. There is nothing we can do here. Closing the bug for now.

**Comment by willard-dawson-nyl** [comment]
Ok, thanks

**Comment by blshkv** [comment]
Good new. I've just received an email from Todd, they have fixed it. I will be removing the fetch restriction soon

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/e64b513b8e4fb7c216f873444014b26980cc96cd
